Hide spoiler text before checking for reaction patterns
you-will-love-each-other/health-bot pull request #50
Opened 2021-06-12 23:18 UTC by slocknad

This PR removes portions of a message that are supposed to be hidden (spoilers) so they don't get reacted to by the bot (avoiding, that way, to make it useless to hide the text)

2021-06-15 00:55 UTC, martin-sweeny requested changes

2021-06-15 17:41 UTC, slocknad commented on auxfunctions.py
> +
Oh sorry, I did not see this! Yes, it does remove those strings, which absolutely doesn't matter since this variable is only used to find the reaction emojis

2021-06-15 17:46 UTC, martin-sweeny commented on auxfunctions.py
> +
> Oh sorry, I did not see this! Yes, it does remove those strings, which absolutely doesn't matter since this variable is only used to find the reaction emojis
@slocknad 

Okay wait. Given a message of content `something ||spoiler|| else`, is the intended result of this function:
1. `something spoiler else` (removing only `||`)
1. `something else` (removing `||` and the content inside)

this function looks like it's only removing `||` and not the content inside

2021-06-15 17:47 UTC, martin-sweeny commented on auxfunctions.py
> +
Either way, this is not a good way to get that done. This should be done with regex search in replace in either case

2021-06-15 17:56 UTC, slocknad commented on auxfunctions.py
> +
It's doing that 2nd thing you described. I'm not sure how regex search and replace works

2021-06-15 17:58 UTC, martin-sweeny commented on auxfunctions.py
> +
@slocknad wanna pair up this week and i can walk you through it?

2021-06-15 18:04 UTC, slocknad commented on auxfunctions.py
> +
I'm going to have a break from exams next week, so let's just do it then

2021-06-15 20:35 UTC, martin-sweeny commented on auxfunctions.py
> +
sounds good

2021-07-09 10:16 UTC, martin-sweeny approved these changes

2021-08-05 10:49 UTC, slocknad commented
This is great, thank you!

2021-08-05 10:49 UTC, merged